/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseContact: typeof import('./src/components/BaseContact.vue')['default']
    BaseContactItem: typeof import('./src/components/BaseContactItem.vue')['default']
    BaseLink: typeof import('./src/components/BaseLink.vue')['default']
    BaseSection: typeof import('./src/components/BaseSection.vue')['default']
    BaseTimeline: typeof import('./src/components/BaseTimeline.vue')['default']
    BaseTimelineEntry: typeof import('./src/components/BaseTimelineEntry.vue')['default']
  }
}
